#!/bin/bash

# === X3_START ===
update-rc.d hobot-adbd remove
systemctl disable hobot-adbd.service
# === X3_END ===

# === X5_START ===
systemctl disable hobot-usb-gadget.service
# === X5_END ===

exit 0
